#!/usr/bin/env python3
"""
Calibration & Fidelity Analysis: STGen vs Intel Berkeley Lab Dataset
=====================================================================

Compares synthetic sensor traces generated by STGen against 2.3 million
real readings from 54 Mica2Dot sensors in the Intel Berkeley Research Lab.

Metrics computed:
  1. Marginal distribution statistics (mean, std, skewness, kurtosis)
  2. Kolmogorov-Smirnov two-sample test (D-statistic, p-value)
  3. Jensen-Shannon divergence between empirical PDFs
  4. Temporal autocorrelation (ACF at lags 1, 5, 10, 20, 50)
  5. Cross-correlation: temperature-humidity coupling
  6. Inter-arrival time distribution comparison
  7. Per-mote variability (coefficient of variation)

Outputs:
  - Console summary tables
  - results/fidelity/ directory with CSV tables and PNG figures
  - LaTeX-ready table fragments for the manuscript
"""

import os
import sys
import math
import random
import json
import warnings
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy import stats as sp_stats
from scipy.spatial.distance import jensenshannon
from statsmodels.tsa.stattools import acf

# ---------------------------------------------------------------------------
# Add project root to path so we can import STGen modules
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(PROJECT_ROOT))

from typing import Tuple
from stgen.sensor_generator import (
    generate_sensor_value,
    _ou_step,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
INTEL_DATA = PROJECT_ROOT / "Intel_dataset" / "data.txt"
OUTPUT_DIR = PROJECT_ROOT / "results" / "fidelity"
N_STGEN_SAMPLES = 100_000        # synthetic samples to generate per modality
N_STGEN_MOTES = 54               # match Intel deployment
STGEN_DURATION_STEPS = 2000      # time-steps per mote for ACF analysis
SEED = 42
RUN_CALIBRATED = True            # also run calibrated ("tuned") models
INTEL_SAMPLE_INTERVAL_SEC = 31.0 # Intel Mica2Dot/TinyDB nominal sampling period

# Intel sensor ranges (for filtering anomalous rows)
INTEL_TEMP_RANGE = (-10, 60)     # °C plausible indoor
INTEL_HUM_RANGE = (0, 100)       # %
INTEL_LIGHT_RANGE = (0, 100000)  # lux
INTEL_VOLT_RANGE = (1.5, 3.5)   # V for Mica2Dot Li-ion

HIST_BINS = 80
ACF_LAGS = [1, 5, 10, 20, 50]
MAX_ACF_LAG = max(ACF_LAGS) + 1


def load_intel_data() -> pd.DataFrame:
    """Parse Intel Berkeley Lab dataset into a DataFrame."""
    print("[1/7] Loading Intel Berkeley Lab dataset …")
    cols = ["date", "time", "epoch", "moteid",
            "temperature", "humidity", "light", "voltage"]
    rows = []
    skipped = 0
    with open(INTEL_DATA, "r") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) != 8:
                skipped += 1
                continue
            try:
                row = {
                    "date": parts[0],
                    "time": parts[1],
                    "epoch": int(parts[2]),
                    "moteid": int(parts[3]),
                    "temperature": float(parts[4]),
                    "humidity": float(parts[5]),
                    "light": float(parts[6]),
                    "voltage": float(parts[7]),
                }
                rows.append(row)
            except (ValueError, IndexError):
                skipped += 1
    df = pd.DataFrame(rows)
    print(f"    Loaded {len(df):,} readings ({skipped:,} malformed rows skipped)")

    # Filter implausible values
    n_before = len(df)
    df = df[
        df["temperature"].between(*INTEL_TEMP_RANGE) &
        df["humidity"].between(*INTEL_HUM_RANGE) &
        df["light"].between(*INTEL_LIGHT_RANGE) &
        df["voltage"].between(*INTEL_VOLT_RANGE)
    ].copy()
    print(f"    After plausibility filter: {len(df):,} ({n_before - len(df):,} removed)")
    return df


# ---------------------------------------------------------------------------
# STGen synthetic trace generators  (mirror the sensor_generator.py models)
# ---------------------------------------------------------------------------

def generate_mvou_temp_hum(n: int, motes: int = 54) -> Tuple[np.ndarray, np.ndarray]:
    """
    Multivariate Ornstein-Uhlenbeck (MVOU) process for Temp & Humidity.
    Uses Cholesky decomposition to correlate the stochastic noise terms.
    """
    dt = 1.0
    theta_T, sigma_T = 0.002, 0.15
    theta_H, sigma_H = 0.001, 0.20
    rho = -0.38  # Tuned: structural coupling + Cholesky ≈ -0.43 target

    T_vals = np.zeros(n)
    H_vals = np.zeros(n)
    per_mote = n // motes

    for m in range(motes):
        start = m * per_mote
        end = min(start + per_mote, n)
        steps = end - start

        # Mote-specific long-term baselines
        mu_T = random.gauss(22.2, 1.0)
        mu_T = max(18, min(30, mu_T))
        mu_H = 53.8 - 0.64 * mu_T

        current_T = mu_T + random.gauss(0, 1)
        current_H = mu_H + random.gauss(0, 3)

        # Generate independent Wiener processes
        dW1 = np.random.normal(0, math.sqrt(dt), steps)
        dW2 = np.random.normal(0, math.sqrt(dt), steps)

        # Cholesky decomposition to create correlated noise
        dZ_T = dW1
        dZ_H = rho * dW1 + math.sqrt(1 - rho**2) * dW2

        for i in range(steps):
            # Regime switching (HVAC/Sunlight) for heavy-tailed variance
            if random.random() < 0.001:
                mu_T += random.gauss(0, 4)
                mu_T = max(15, min(40, mu_T))
                mu_H = 53.8 - 0.64 * mu_T

            # SDE updates using correlated noise
            current_T += theta_T * (mu_T - current_T) * dt + sigma_T * dZ_T[i]
            current_H += theta_H * (mu_H - current_H) * dt + sigma_H * dZ_H[i]

            current_H = max(0.0, min(100.0, current_H))

            T_vals[start + i] = current_T
            H_vals[start + i] = current_H

    return T_vals, H_vals


def generate_stgen_light(n: int, motes: int = 54) -> np.ndarray:
    """Light: bimodal OU with regime switching (updated model).
    
    Dark regime: OU around μ=28, Bright regime: OU around μ=639.
    """
    per_mote = n // motes
    vals = np.zeros(n)
    for m in range(motes):
        start = m * per_mote
        end = start + per_mote
        bright = random.random() > 0.375  # 37.5% start dark
        current = 639.0 if bright else 28.0
        for i in range(start, min(end, n)):
            if bright:
                if random.random() < 0.012:
                    bright = False
                target, sigma_l = 639.0, 80.0
            else:
                if random.random() < 0.02:
                    bright = True
                target, sigma_l = 28.0, 5.0
            current = _ou_step(current, target, theta=0.01, sigma=sigma_l,
                               lo=0, hi=100000)
            vals[i] = current
    return vals


def generate_stgen_voltage(n: int, motes: int = 54) -> np.ndarray:
    """Voltage: OU process with slow discharge drift (updated model).
    
    Calibrated: μ≈2.56V, σ≈0.12V for Mica2Dot Li-ion.
    """
    per_mote = n // motes
    vals = np.zeros(n)
    for m in range(motes):
        start = m * per_mote
        end = start + per_mote
        v_mean = random.gauss(2.56, 0.08)
        current = v_mean
        for i in range(start, min(end, n)):
            v_mean -= 0.00001  # slow discharge
            current = _ou_step(current, v_mean, theta=0.001, sigma=0.005,
                               lo=1.5, hi=3.5)
            vals[i] = current
    return vals


# ---------------------------------------------------------------------------
# Calibration: Fit models to Intel data, then generate "tuned" STGen traces
# ---------------------------------------------------------------------------

def calibrate_ou_params(series: np.ndarray, dt: float = 1.0):
    """Estimate OU process parameters (theta, mu, sigma) from a time series.
    
    Uses method-of-moments:
      mu = sample mean
            Auto-correlation at lag-1: rho_1 = exp(-theta*dt)
        → theta = -ln(rho_1) / dt
      sigma = std(residuals) * sqrt(2*theta)

        Note:
            dt is in model step units. In this script, one step corresponds to one
            Intel sample interval (~31s), so default dt=1.0 is intentional.
    """
    mu = float(np.mean(series))
    # Lag-1 autocorrelation
    centered = series - mu
    if len(centered) < 3:
        return 0.1, mu, 0.5  # fallback
    rho1 = np.corrcoef(centered[:-1], centered[1:])[0, 1]
    rho1 = max(rho1, 0.001)  # avoid log(0)
    theta = -math.log(rho1) / dt
    theta = max(theta, 0.001)
    # Residual volatility
    residuals = centered[1:] - rho1 * centered[:-1]
    sig_res = float(np.std(residuals))
    sigma = sig_res * math.sqrt(2 * theta)
    return theta, mu, sigma


def ou_temperature_calibrated(current, mean, dt, theta, sigma):
    """Calibrated OU temperature step."""
    dW = random.gauss(0, 1) * math.sqrt(dt)
    dT = theta * (mean - current) * dt + sigma * dW
    max_rate = 0.5 / 60
    dT = max(-max_rate * dt, min(max_rate * dt, dT))
    return current + dT


def calibrate_humidity_model(intel_temp, intel_hum):
    """Fit linear model: humidity = a + b*temperature + noise.
    
    Returns (a, b, noise_std).
    """
    # Use numpy polyfit (degree 1)
    mask = np.isfinite(intel_temp) & np.isfinite(intel_hum)
    t = intel_temp[mask]
    h = intel_hum[mask]
    b, a = np.polyfit(t, h, 1)
    residuals = h - (a + b * t)
    noise_std = float(np.std(residuals))
    return float(a), float(b), noise_std


def calibrate_light_model(intel_light):
    """Fit a mixture model for light (bimodal: dark vs bright).
    
    Simple approach: two-component Gaussian mixture estimated via
    threshold splitting at the median.
    Returns (mu1, sig1, weight1, mu2, sig2).
    """
    arr = intel_light[np.isfinite(intel_light)]
    # Use 100 lux threshold to split dark/bright modes
    threshold = 100.0
    dark = arr[arr <= threshold]
    bright = arr[arr > threshold]
    w_dark = len(dark) / len(arr)
    mu1 = float(np.mean(dark)) if len(dark) > 0 else 10.0
    sig1 = float(np.std(dark)) if len(dark) > 1 else 30.0
    mu2 = float(np.mean(bright)) if len(bright) > 0 else 500.0
    sig2 = float(np.std(bright)) if len(bright) > 1 else 200.0
    return mu1, sig1, w_dark, mu2, sig2


def generate_calibrated_mvou_temp_hum(n, motes, theta_T, sigma_T,
                                       a_hum, b_hum, noise_hum,
                                       intel_temp, rho=-0.38):
    """Calibrated MVOU temperature-humidity with Cholesky-correlated noise."""
    global_mean = float(np.mean(intel_temp))
    global_std = float(np.std(intel_temp))
    dt = 1.0
    theta_H = 0.001
    sigma_H = noise_hum * 0.05

    T_vals = np.zeros(n)
    H_vals = np.zeros(n)
    per_mote = n // motes

    for m_idx in range(motes):
        start = m_idx * per_mote
        end = min(start + per_mote, n)
        steps = end - start

        mu_T = random.gauss(global_mean, global_std * 0.4)
        mu_H = a_hum + b_hum * mu_T

        current_T = mu_T + random.gauss(0, 1)
        current_H = mu_H + random.gauss(0, 3)

        dW1 = np.random.normal(0, math.sqrt(dt), steps)
        dW2 = np.random.normal(0, math.sqrt(dt), steps)
        dZ_T = dW1
        dZ_H = rho * dW1 + math.sqrt(1 - rho**2) * dW2

        for i in range(steps):
            dT = theta_T * (mu_T - current_T) * dt + sigma_T * dZ_T[i]
            max_rate = 0.5 / 60
            dT = max(-max_rate * dt, min(max_rate * dt, dT))
            current_T += dT

            target_H = a_hum + b_hum * current_T
            current_H += theta_H * (target_H - current_H) * dt + sigma_H * dZ_H[i]
            current_H = max(0.0, min(100.0, current_H))

            T_vals[start + i] = current_T
            H_vals[start + i] = current_H

    return T_vals, H_vals


def generate_calibrated_light(n, mu1, sig1, w_dark, mu2, sig2, motes=54):
    """Generate light from calibrated bimodal OU with regime switching."""
    vals = np.zeros(n)
    per_mote = n // motes
    for m in range(motes):
        start = m * per_mote
        end = start + per_mote
        dark = random.random() < w_dark
        current = mu1 if dark else mu2
        for i in range(start, min(end, n)):
            if dark:
                if random.random() < 0.02: dark = False
                target, sigma_l = mu1, sig1 * 0.15
            else:
                if random.random() < 0.012: dark = True
                target, sigma_l = mu2, sig2 * 0.14
            current = _ou_step(current, target, theta=0.01, sigma=sigma_l,
                               lo=0, hi=100000)
            vals[i] = current
    return vals


def generate_calibrated_voltage(n, intel_volt, motes=54):
    """Voltage: calibrated OU with slow discharge drift."""
    mu = float(np.mean(intel_volt))
    sigma = float(np.std(intel_volt))
    vals = np.zeros(n)
    per_mote = n // motes
    for m in range(motes):
        start = m * per_mote
        end = start + per_mote
        v_mean = random.gauss(mu, sigma * 0.7)
        current = v_mean
        for i in range(start, min(end, n)):
            v_mean -= 0.00001
            current = _ou_step(current, v_mean, theta=0.001, sigma=sigma * 0.05,
                               lo=1.5, hi=3.5)
            vals[i] = current
    return vals


# ---------------------------------------------------------------------------
# Statistical helpers
# ---------------------------------------------------------------------------

def compute_moments(arr: np.ndarray) -> dict:
    """Return mean, std, skewness, kurtosis."""
    return {
        "mean": float(np.mean(arr)),
        "std": float(np.std(arr, ddof=1)),
        "skew": float(sp_stats.skew(arr)),
        "kurtosis": float(sp_stats.kurtosis(arr)),  # excess kurtosis
        "median": float(np.median(arr)),
        "q25": float(np.percentile(arr, 25)),
        "q75": float(np.percentile(arr, 75)),
    }


def ks_test(real: np.ndarray, synth: np.ndarray) -> dict:
    """Two-sample Kolmogorov-Smirnov test."""
    d, p = sp_stats.ks_2samp(real, synth)
    return {"D": float(d), "p": float(p)}


def js_divergence(real: np.ndarray, synth: np.ndarray, bins: int = HIST_BINS) -> float:
    """Jensen-Shannon divergence between two empirical distributions."""
    lo = min(real.min(), synth.min())
    hi = max(real.max(), synth.max())
    edges = np.linspace(lo, hi, bins + 1)
    p, _ = np.histogram(real, bins=edges, density=True)
    q, _ = np.histogram(synth, bins=edges, density=True)
    # Add tiny epsilon for numerical stability
    p = p + 1e-12
    q = q + 1e-12
    p = p / p.sum()
    q = q / q.sum()
    return float(jensenshannon(p, q) ** 2)  # squared = actual JSD


def compute_acf_lags(series: np.ndarray, lags: list) -> dict:
    """Compute ACF at specific lags."""
    if len(series) < MAX_ACF_LAG + 10:
        return {l: float("nan") for l in lags}
    acf_vals = acf(series, nlags=MAX_ACF_LAG, fft=True)
    return {l: float(acf_vals[l]) for l in lags if l < len(acf_vals)}


def compute_cross_corr(x: np.ndarray, y: np.ndarray) -> float:
    """Pearson r between two equal-length arrays."""
    if len(x) != len(y):
        n = min(len(x), len(y))
        x, y = x[:n], y[:n]
    r, _ = sp_stats.pearsonr(x, y)
    return float(r)


# ---------------------------------------------------------------------------
# Per-mote variability
# ---------------------------------------------------------------------------

def per_mote_cv(df: pd.DataFrame, col: str) -> dict:
    """Coefficient of variation across motes."""
    grouped = df.groupby("moteid")[col]
    means = grouped.mean()
    stds = grouped.std()
    cvs = (stds / means.abs().clip(lower=1e-6))
    return {
        "mean_cv": float(cvs.mean()),
        "std_cv": float(cvs.std()),
        "min_cv": float(cvs.min()),
        "max_cv": float(cvs.max()),
    }


# ---------------------------------------------------------------------------
# Inter-arrival time analysis
# ---------------------------------------------------------------------------

def compute_iat_stats(df: pd.DataFrame) -> dict:
    """Compute inter-arrival time statistics from Intel dataset."""
    # Combine date+time into seconds
    times = pd.to_datetime(df["date"] + " " + df["time"], format="mixed", errors="coerce")
    iats_all = []
    for mote_id in df["moteid"].unique():
        mask = df["moteid"] == mote_id
        mote_times = times[mask].dropna().sort_values()
        if len(mote_times) < 2:
            continue
        diffs = mote_times.diff().dt.total_seconds().dropna()
        # Filter to plausible range (1s to 300s) — remove outlier gaps
        diffs = diffs[(diffs > 1) & (diffs < 300)]
        iats_all.extend(diffs.tolist())
    arr = np.array(iats_all)
    return {
        "mean": float(np.mean(arr)),
        "std": float(np.std(arr)),
        "median": float(np.median(arr)),
        "values": arr,
    }


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def plot_distribution_comparison(real, synth, modality, unit, outpath):
    """Side-by-side histogram + Q-Q plot."""
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))

    # --- Histogram ---
    lo, hi = np.percentile(np.concatenate([real, synth]), [0.5, 99.5])
    bins = np.linspace(lo, hi, HIST_BINS)
    axes[0].hist(real, bins=bins, density=True, alpha=0.6, label="Intel Lab", color="#2196F3")
    axes[0].hist(synth, bins=bins, density=True, alpha=0.6, label="STGen", color="#FF5722")
    axes[0].set_xlabel(f"{modality} ({unit})")
    axes[0].set_ylabel("Density")
    axes[0].set_title(f"{modality} Distribution")
    axes[0].legend()

    # --- CDF ---
    real_sorted = np.sort(real)
    synth_sorted = np.sort(synth)
    axes[1].plot(real_sorted, np.linspace(0, 1, len(real_sorted)), label="Intel Lab", color="#2196F3")
    axes[1].plot(synth_sorted, np.linspace(0, 1, len(synth_sorted)), label="STGen", color="#FF5722")
    axes[1].set_xlabel(f"{modality} ({unit})")
    axes[1].set_ylabel("CDF")
    axes[1].set_title(f"{modality} ECDF")
    axes[1].legend()

    # --- Q-Q plot ---
    # subsample for speed
    n_qq = min(5000, len(real), len(synth))
    qq_real = np.sort(np.random.choice(real, n_qq, replace=False))
    qq_synth = np.sort(np.random.choice(synth, n_qq, replace=False))
    # Align lengths by interpolating quantiles
    quantiles = np.linspace(0, 1, n_qq)
    real_q = np.quantile(real, quantiles)
    synth_q = np.quantile(synth, quantiles)
    axes[2].scatter(real_q, synth_q, s=4, alpha=0.5, color="#4CAF50")
    diag_min = min(real_q.min(), synth_q.min())
    diag_max = max(real_q.max(), synth_q.max())
    axes[2].plot([diag_min, diag_max], [diag_min, diag_max], "k--", lw=1)
    axes[2].set_xlabel(f"Intel Lab quantiles")
    axes[2].set_ylabel(f"STGen quantiles")
    axes[2].set_title(f"{modality} Q-Q Plot")

    fig.tight_layout()
    fig.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_acf_comparison(real_acf, synth_acf, modality, outpath):
    """Bar chart comparing ACF values at key lags."""
    lags = sorted(real_acf.keys())
    r_vals = [real_acf[l] for l in lags]
    s_vals = [synth_acf[l] for l in lags]

    x = np.arange(len(lags))
    w = 0.35
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(x - w/2, r_vals, w, label="Intel Lab", color="#2196F3")
    ax.bar(x + w/2, s_vals, w, label="STGen", color="#FF5722")
    ax.set_xticks(x)
    ax.set_xticklabels([f"lag {l}" for l in lags])
    ax.set_ylabel("Autocorrelation")
    ax.set_title(f"{modality} ACF Comparison")
    ax.legend()
    fig.tight_layout()
    fig.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_iat_comparison(intel_iat, stgen_iat, outpath):
    """Compare inter-arrival time distributions."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    bins = np.linspace(0, 120, 80)
    axes[0].hist(intel_iat, bins=bins, density=True, alpha=0.6, label="Intel Lab", color="#2196F3")
    axes[0].hist(stgen_iat, bins=bins, density=True, alpha=0.6, label="STGen (31s fixed)", color="#FF5722")
    axes[0].set_xlabel("Inter-Arrival Time (s)")
    axes[0].set_ylabel("Density")
    axes[0].set_title("IAT Distribution")
    axes[0].legend()

    # Log-scale
    axes[1].hist(intel_iat, bins=100, density=True, alpha=0.6, label="Intel Lab", color="#2196F3", log=True)
    axes[1].hist(stgen_iat, bins=100, density=True, alpha=0.6, label="STGen", color="#FF5722", log=True)
    axes[1].set_xlabel("Inter-Arrival Time (s)")
    axes[1].set_ylabel("Density (log)")
    axes[1].set_title("IAT Distribution (log scale)")
    axes[1].legend()

    fig.tight_layout()
    fig.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_cross_correlation(intel_temp, intel_hum, stgen_temp, stgen_hum, outpath):
    """Scatter plots showing temp-humidity coupling."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    n = min(10000, len(intel_temp), len(intel_hum))
    idx = np.random.choice(len(intel_temp), n, replace=False)
    axes[0].scatter(intel_temp[idx], intel_hum[idx], s=2, alpha=0.3, color="#2196F3")
    axes[0].set_xlabel("Temperature (°C)")
    axes[0].set_ylabel("Humidity (%)")
    r_intel = compute_cross_corr(intel_temp, intel_hum)
    axes[0].set_title(f"Intel Lab (r = {r_intel:.3f})")

    n2 = min(10000, len(stgen_temp), len(stgen_hum))
    idx2 = np.random.choice(len(stgen_temp), n2, replace=False)
    axes[1].scatter(stgen_temp[idx2], stgen_hum[idx2], s=2, alpha=0.3, color="#FF5722")
    axes[1].set_xlabel("Temperature (°C)")
    axes[1].set_ylabel("Humidity (%)")
    r_stgen = compute_cross_corr(stgen_temp, stgen_hum)
    axes[1].set_title(f"STGen (r = {r_stgen:.3f})")

    fig.suptitle("Temperature–Humidity Cross-Correlation", fontsize=13)
    fig.tight_layout()
    fig.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_summary_dashboard(results, outpath):
    """Single dashboard figure summarizing all fidelity metrics."""
    modalities = ["Temperature", "Humidity", "Light", "Voltage"]
    metrics = ["KS D-stat", "JSD", "Mean Δ%", "Std Δ%"]

    data = np.zeros((len(modalities), len(metrics)))
    for i, mod in enumerate(modalities):
        r = results[mod.lower()]
        data[i, 0] = r["ks"]["D"]
        data[i, 1] = r["jsd"]
        intel_mean = abs(r["intel"]["mean"]) if abs(r["intel"]["mean"]) > 0.01 else 1.0
        data[i, 2] = abs(r["intel"]["mean"] - r["stgen"]["mean"]) / intel_mean * 100
        intel_std = r["intel"]["std"] if r["intel"]["std"] > 0.01 else 1.0
        data[i, 3] = abs(r["intel"]["std"] - r["stgen"]["std"]) / intel_std * 100

    fig, ax = plt.subplots(figsize=(8, 4))
    im = ax.imshow(data, cmap="YlOrRd", aspect="auto")
    ax.set_xticks(range(len(metrics)))
    ax.set_xticklabels(metrics, fontsize=10)
    ax.set_yticks(range(len(modalities)))
    ax.set_yticklabels(modalities, fontsize=10)
    for i in range(len(modalities)):
        for j in range(len(metrics)):
            val = data[i, j]
            fmt = f"{val:.3f}" if j < 2 else f"{val:.1f}%"
            ax.text(j, i, fmt, ha="center", va="center", fontsize=9,
                    color="white" if val > data.max() * 0.6 else "black")
    ax.set_title("STGen Fidelity vs Intel Berkeley Lab Data", fontsize=12)
    fig.colorbar(im, ax=ax, shrink=0.8)
    fig.tight_layout()
    fig.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# LaTeX table generation
# ---------------------------------------------------------------------------

def generate_latex_tables(results, cross_corr, iat_stats, outpath):
    """Write LaTeX table fragments for the manuscript."""
    lines = []
    lines.append(r"% Auto-generated by run_fidelity_analysis.py")
    lines.append(r"% Table: Marginal Distribution Comparison")
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{Marginal distribution comparison: Intel Berkeley Lab vs.\ STGen synthetic traces.}")
    lines.append(r"\label{tab:fidelity-marginal}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{l|rr|rr|r|r}")
    lines.append(r"\hline")
    lines.append(r"\textbf{Modality} & \multicolumn{2}{c|}{\textbf{Intel Lab}} & \multicolumn{2}{c|}{\textbf{STGen}} & \textbf{KS $D$} & \textbf{JSD} \\")
    lines.append(r" & $\mu$ & $\sigma$ & $\mu$ & $\sigma$ & & \\")
    lines.append(r"\hline")

    for mod in ["temperature", "humidity", "light", "voltage"]:
        r = results[mod]
        unit = {"temperature": "°C", "humidity": "\\%", "light": "lux", "voltage": "V"}[mod]
        name = mod.capitalize()
        lines.append(
            f"{name} ({unit}) & {r['intel']['mean']:.2f} & {r['intel']['std']:.2f} "
            f"& {r['stgen']['mean']:.2f} & {r['stgen']['std']:.2f} "
            f"& {r['ks']['D']:.4f} & {r['jsd']:.4f} \\\\"
        )

    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    # --- ACF Table ---
    lines.append("")
    lines.append(r"% Table: Autocorrelation Comparison")
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{Autocorrelation function (ACF) at selected lags: Intel Lab vs.\ STGen.}")
    lines.append(r"\label{tab:fidelity-acf}")
    lines.append(r"\small")

    lag_cols = " ".join([f"r@{{\\hspace{{4pt}}}}" for _ in ACF_LAGS])
    lines.append(r"\begin{tabular}{l|" + lag_cols + "|" + lag_cols + "}")
    lines.append(r"\hline")
    lag_hdr_intel = " & ".join([f"$\\ell$={l}" for l in ACF_LAGS])
    lag_hdr_stgen = " & ".join([f"$\\ell$={l}" for l in ACF_LAGS])
    lines.append(r"\textbf{Modality} & \multicolumn{" + str(len(ACF_LAGS)) + r"}{c|}{\textbf{Intel Lab ACF}} & \multicolumn{" + str(len(ACF_LAGS)) + r"}{c}{\textbf{STGen ACF}} \\")
    lines.append(r" & " + lag_hdr_intel + " & " + lag_hdr_stgen + r" \\")
    lines.append(r"\hline")

    for mod in ["temperature", "humidity", "light", "voltage"]:
        r = results[mod]
        name = mod.capitalize()
        intel_acf = " & ".join([f"{r['intel_acf'].get(l, float('nan')):.3f}" for l in ACF_LAGS])
        stgen_acf = " & ".join([f"{r['stgen_acf'].get(l, float('nan')):.3f}" for l in ACF_LAGS])
        lines.append(f"{name} & {intel_acf} & {stgen_acf} \\\\")

    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    # --- Cross-correlation ---
    lines.append("")
    lines.append(r"% Table: Cross-Correlation & IAT")
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{Cross-correlation and inter-arrival time comparison.}")
    lines.append(r"\label{tab:fidelity-crosscorr}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{l|r|r}")
    lines.append(r"\hline")
    lines.append(r"\textbf{Metric} & \textbf{Intel Lab} & \textbf{STGen} \\")
    lines.append(r"\hline")
    lines.append(f"Temp–Humidity $r$ & {cross_corr['intel']:.3f} & {cross_corr['stgen']:.3f} \\\\")
    lines.append(f"IAT mean (s) & {iat_stats['intel_mean']:.1f} & {iat_stats['stgen_mean']:.1f} \\\\")
    lines.append(f"IAT std (s) & {iat_stats['intel_std']:.1f} & {iat_stats['stgen_std']:.1f} \\\\")
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    with open(outpath, "w") as f:
        f.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Main analysis
# ---------------------------------------------------------------------------

def main():
    random.seed(SEED)
    np.random.seed(SEED)
    warnings.filterwarnings("ignore", category=RuntimeWarning)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # -----------------------------------------------------------------------
    # 1. Load Intel data
    # -----------------------------------------------------------------------
    intel_df = load_intel_data()

    intel_temp = intel_df["temperature"].values
    intel_hum = intel_df["humidity"].values
    intel_light = intel_df["light"].values
    intel_volt = intel_df["voltage"].values

    # -----------------------------------------------------------------------
    # 2. Generate STGen synthetic traces
    # -----------------------------------------------------------------------
    print("[2/7] Generating STGen synthetic traces …")
    stgen_temp, stgen_hum = generate_mvou_temp_hum(N_STGEN_SAMPLES, motes=N_STGEN_MOTES)
    stgen_light = generate_stgen_light(N_STGEN_SAMPLES, motes=N_STGEN_MOTES)
    stgen_volt = generate_stgen_voltage(N_STGEN_SAMPLES, motes=N_STGEN_MOTES)
    print(f"    Generated {N_STGEN_SAMPLES:,} samples per modality")

    # -----------------------------------------------------------------------
    # 3. Marginal distribution statistics
    # -----------------------------------------------------------------------
    print("[3/7] Computing marginal distribution statistics …")
    results = {}
    modalities = {
        "temperature": (intel_temp, stgen_temp, "°C"),
        "humidity": (intel_hum, stgen_hum, "%"),
        "light": (intel_light, stgen_light, "lux"),
        "voltage": (intel_volt, stgen_volt, "V"),
    }

    for mod, (real, synth, unit) in modalities.items():
        results[mod] = {
            "intel": compute_moments(real),
            "stgen": compute_moments(synth),
            "ks": ks_test(real, synth),
            "jsd": js_divergence(real, synth),
            "unit": unit,
        }

    # -----------------------------------------------------------------------
    # 4. Temporal autocorrelation
    # -----------------------------------------------------------------------
    print("[4/7] Computing temporal autocorrelation (ACF) …")

    # Intel ACF: pick a high-data mote, sorted by timestamp
    for mod, col in [("temperature", "temperature"), ("humidity", "humidity"),
                     ("light", "light"), ("voltage", "voltage")]:
        # Use mote with most data for clean ACF
        mote_counts = intel_df.groupby("moteid")[col].count()
        best_mote = mote_counts.idxmax()
        mote_series = intel_df[intel_df["moteid"] == best_mote].sort_values(["date", "time"])[col].values

        results[mod]["intel_acf"] = compute_acf_lags(mote_series, ACF_LAGS)

    # STGen ACF: generate long single-mote MVOU traces
    N_ACF = STGEN_DURATION_STEPS
    rho_acf = -0.38
    theta_T_acf, sigma_T_acf = 0.002, 0.15
    theta_H_acf, sigma_H_acf = 0.001, 0.20

    # Temperature + Humidity via Cholesky-correlated noise
    stgen_temp_series = np.zeros(N_ACF)
    stgen_hum_series = np.zeros(N_ACF)
    mean_t = 22.0
    current_t = 22.0
    mean_h = 53.8 - 0.64 * mean_t
    current_h = mean_h
    dW1_acf = np.random.normal(0, 1.0, N_ACF)
    dW2_acf = np.random.normal(0, 1.0, N_ACF)
    dZ_T_acf = dW1_acf
    dZ_H_acf = rho_acf * dW1_acf + math.sqrt(1 - rho_acf**2) * dW2_acf
    for i in range(N_ACF):
        if random.random() < 0.001:
            mean_t += random.gauss(0, 4)
            mean_t = max(15, min(40, mean_t))
            mean_h = 53.8 - 0.64 * mean_t
        current_t += theta_T_acf * (mean_t - current_t) + sigma_T_acf * dZ_T_acf[i]
        current_h += theta_H_acf * (mean_h - current_h) + sigma_H_acf * dZ_H_acf[i]
        current_h = max(0.0, min(100.0, current_h))
        stgen_temp_series[i] = current_t
        stgen_hum_series[i] = current_h
    results["temperature"]["stgen_acf"] = compute_acf_lags(stgen_temp_series, ACF_LAGS)
    results["humidity"]["stgen_acf"] = compute_acf_lags(stgen_hum_series, ACF_LAGS)

    # Light: bimodal OU with regime switching (increased bright sigma)
    stgen_light_series = np.zeros(N_ACF)
    bright = random.random() > 0.375
    l_current = 639.0 if bright else 28.0
    for i in range(N_ACF):
        if bright:
            if random.random() < 0.012: bright = False
            target_l, sig_l = 639.0, 80.0
        else:
            if random.random() < 0.02: bright = True
            target_l, sig_l = 28.0, 5.0
        l_current = _ou_step(l_current, target_l, theta=0.01, sigma=sig_l,
                             lo=0, hi=100000)
        stgen_light_series[i] = l_current
    results["light"]["stgen_acf"] = compute_acf_lags(stgen_light_series, ACF_LAGS)

    # Voltage: OU with slow discharge
    stgen_volt_series = np.zeros(N_ACF)
    v_mean = 2.56
    v_current = 2.56
    for i in range(N_ACF):
        v_mean -= 0.00001
        v_current = _ou_step(v_current, v_mean, theta=0.001, sigma=0.005,
                             lo=1.5, hi=3.5)
        stgen_volt_series[i] = v_current
    results["voltage"]["stgen_acf"] = compute_acf_lags(stgen_volt_series, ACF_LAGS)

    # -----------------------------------------------------------------------
    # 5. Cross-correlation: temperature–humidity
    # -----------------------------------------------------------------------
    print("[5/7] Computing cross-correlations …")
    cross_corr = {
        "intel": compute_cross_corr(intel_temp, intel_hum),
        "stgen": compute_cross_corr(stgen_temp, stgen_hum),
    }

    # -----------------------------------------------------------------------
    # 6. Inter-arrival time comparison
    # -----------------------------------------------------------------------
    print("[6/7] Computing inter-arrival time statistics …")
    intel_iat = compute_iat_stats(intel_df)
    # STGen nominal: Intel-referenced 31s interval (for fidelity comparison only)
    stgen_iat_values = np.full(10000, INTEL_SAMPLE_INTERVAL_SEC)
    stgen_iat_weibull = np.array([INTEL_SAMPLE_INTERVAL_SEC * ((-math.log(max(random.random(), 1e-10))) ** (1.0 / 0.8))
                                   for _ in range(10000)])
    iat_comparison = {
        "intel_mean": intel_iat["mean"],
        "intel_std": intel_iat["std"],
        "stgen_mean": INTEL_SAMPLE_INTERVAL_SEC,
        "stgen_std": 0.0,
        "stgen_weibull_mean": float(np.mean(stgen_iat_weibull)),
        "stgen_weibull_std": float(np.std(stgen_iat_weibull)),
    }

    # -----------------------------------------------------------------------
    # 7. Per-mote variability
    # -----------------------------------------------------------------------
    print("[7/7] Computing per-mote variability …")
    mote_cv = {}
    for col in ["temperature", "humidity", "light", "voltage"]:
        mote_cv[col] = per_mote_cv(intel_df, col)

    # ===================================================================
    # OUTPUT: Console summary
    # ===================================================================
    print("\n" + "=" * 80)
    print("CALIBRATION & FIDELITY ANALYSIS: STGen vs Intel Berkeley Lab")
    print("=" * 80)

    # Marginal summary
    print("\n┌─────────────────────────────────────────────────────────────────────────────┐")
    print("│  MARGINAL DISTRIBUTION COMPARISON                                           │")
    print("├───────────────┬──────────────────────┬──────────────────────┬────────┬───────┤")
    print("│  Modality     │  Intel Lab (μ ± σ)   │  STGen (μ ± σ)       │  KS D  │  JSD  │")
    print("├───────────────┼──────────────────────┼──────────────────────┼────────┼───────┤")
    for mod in ["temperature", "humidity", "light", "voltage"]:
        r = results[mod]
        name = mod.capitalize().ljust(13)
        intel_str = f"{r['intel']['mean']:7.2f} ± {r['intel']['std']:6.2f}".ljust(20)
        stgen_str = f"{r['stgen']['mean']:7.2f} ± {r['stgen']['std']:6.2f}".ljust(20)
        ks_str = f"{r['ks']['D']:.4f}"
        jsd_str = f"{r['jsd']:.4f}"
        print(f"│  {name} │  {intel_str} │  {stgen_str} │ {ks_str} │{jsd_str} │")
    print("└───────────────┴──────────────────────┴──────────────────────┴────────┴───────┘")

    # ACF summary
    print("\n┌──────────────────────────────────────────────────────────────────────────────┐")
    print("│  AUTOCORRELATION (ACF) AT KEY LAGS                                           │")
    print("├───────────────┬────────────────────────────┬─────────────────────────────────┤")
    lag_hdr = "  ".join([f"L{l:>2}" for l in ACF_LAGS])
    print(f"│  Modality     │  Intel: {lag_hdr}   │  STGen: {lag_hdr}   │")
    print("├───────────────┼────────────────────────────┼─────────────────────────────────┤")
    for mod in ["temperature", "humidity", "light", "voltage"]:
        r = results[mod]
        name = mod.capitalize().ljust(13)
        intel_acf_str = "  ".join([f"{r['intel_acf'].get(l, float('nan')):5.3f}" for l in ACF_LAGS])
        stgen_acf_str = "  ".join([f"{r['stgen_acf'].get(l, float('nan')):5.3f}" for l in ACF_LAGS])
        print(f"│  {name} │  {intel_acf_str} │  {stgen_acf_str}  │")
    print("└───────────────┴────────────────────────────┴─────────────────────────────────┘")

    # Cross-correlation
    print(f"\n  Temperature–Humidity Cross-Correlation:")
    print(f"    Intel Lab:  r = {cross_corr['intel']:.4f}")
    print(f"    STGen:      r = {cross_corr['stgen']:.4f}")

    # IAT
    print(f"\n  Inter-Arrival Time:")
    print(f"    Intel Lab:  μ = {iat_comparison['intel_mean']:.1f}s, σ = {iat_comparison['intel_std']:.1f}s")
    print(f"    STGen (fixed):  μ = {iat_comparison['stgen_mean']:.1f}s, σ = {iat_comparison['stgen_std']:.1f}s")
    print(f"    STGen (Weibull k=0.8): μ = {iat_comparison['stgen_weibull_mean']:.1f}s, σ = {iat_comparison['stgen_weibull_std']:.1f}s")

    # Per-mote variability
    print("\n  Per-Mote Coefficient of Variation (Intel Lab):")
    for col in ["temperature", "humidity", "light", "voltage"]:
        cv = mote_cv[col]
        print(f"    {col.capitalize():13s}: mean CV = {cv['mean_cv']:.3f} (range {cv['min_cv']:.3f}–{cv['max_cv']:.3f})")

    # ===================================================================
    # OUTPUT: Figures
    # ===================================================================
    print(f"\nGenerating figures in {OUTPUT_DIR}/ …")

    for mod, (real, synth, unit) in modalities.items():
        plot_distribution_comparison(
            real, synth, mod.capitalize(), unit,
            OUTPUT_DIR / f"dist_{mod}.png"
        )

    for mod in ["temperature", "humidity", "light", "voltage"]:
        r = results[mod]
        plot_acf_comparison(
            r["intel_acf"], r["stgen_acf"], mod.capitalize(),
            OUTPUT_DIR / f"acf_{mod}.png"
        )

    plot_iat_comparison(
        intel_iat["values"], stgen_iat_weibull,
        OUTPUT_DIR / "iat_comparison.png"
    )

    plot_cross_correlation(
        intel_temp, intel_hum, stgen_temp, stgen_hum,
        OUTPUT_DIR / "cross_corr_temp_hum.png"
    )

    plot_summary_dashboard(results, OUTPUT_DIR / "fidelity_dashboard.png")

    # ===================================================================
    # OUTPUT: LaTeX tables
    # ===================================================================
    generate_latex_tables(results, cross_corr, iat_comparison,
                          OUTPUT_DIR / "fidelity_tables.tex")
    print(f"  LaTeX tables → {OUTPUT_DIR / 'fidelity_tables.tex'}")

    # ===================================================================
    # OUTPUT: JSON results
    # ===================================================================
    json_results = {
        "marginal": {},
        "acf": {},
        "cross_correlation": cross_corr,
        "inter_arrival_time": {k: v for k, v in iat_comparison.items()},
        "per_mote_cv": mote_cv,
    }
    for mod in ["temperature", "humidity", "light", "voltage"]:
        r = results[mod]
        json_results["marginal"][mod] = {
            "intel": r["intel"],
            "stgen": r["stgen"],
            "ks_D": r["ks"]["D"],
            "ks_p": r["ks"]["p"],
            "jsd": r["jsd"],
        }
        json_results["acf"][mod] = {
            "intel": {str(k): v for k, v in r["intel_acf"].items()},
            "stgen": {str(k): v for k, v in r["stgen_acf"].items()},
        }

    with open(OUTPUT_DIR / "fidelity_results.json", "w") as f:
        json.dump(json_results, f, indent=2)
    print(f"  JSON results → {OUTPUT_DIR / 'fidelity_results.json'}")

    # ===================================================================
    # Fidelity Score Summary
    # ===================================================================
    print("\n" + "=" * 80)
    print("FIDELITY SCORECARD")
    print("=" * 80)
    overall_scores = []
    for mod in ["temperature", "humidity", "light", "voltage"]:
        r = results[mod]
        # Score: 1 - KS_D (closer to 1 = better match)
        ks_score = 1.0 - r["ks"]["D"]
        # Score: 1 - JSD (closer to 1 = better match)
        jsd_score = 1.0 - min(r["jsd"], 1.0)
        # ACF similarity: 1 - mean |ACF_intel - ACF_stgen| across lags
        acf_diffs = []
        for l in ACF_LAGS:
            i_acf = r["intel_acf"].get(l, 0)
            s_acf = r["stgen_acf"].get(l, 0)
            if not (math.isnan(i_acf) or math.isnan(s_acf)):
                acf_diffs.append(abs(i_acf - s_acf))
        acf_score = 1.0 - (np.mean(acf_diffs) if acf_diffs else 0.5)

        composite = (ks_score + jsd_score + acf_score) / 3.0
        overall_scores.append(composite)
        print(f"  {mod.capitalize():13s}:  KS={ks_score:.3f}  JSD={jsd_score:.3f}  ACF={acf_score:.3f}  → Composite={composite:.3f}")

    print(f"\n  Overall Fidelity Score (Default): {np.mean(overall_scores):.3f} / 1.000")
    print("=" * 80)

    # ===================================================================
    # CALIBRATED MODEL: fit to Intel data, re-generate, compare
    # ===================================================================
    if RUN_CALIBRATED:
        print("\n" + "=" * 80)
        print("PHASE 2: CALIBRATED MODEL (parameters fitted to Intel data)")
        print("=" * 80)

        # --- Calibrate OU temperature ---
        print("\n  Fitting OU parameters from Intel temperature …")
        mote_counts = intel_df.groupby("moteid")["temperature"].count()
        best_mote = mote_counts.idxmax()
        best_series = intel_df[intel_df["moteid"] == best_mote].sort_values(
            ["date", "time"])["temperature"].values
        theta_cal, mu_cal, sigma_cal = calibrate_ou_params(best_series)
        print(f"    θ = {theta_cal:.4f},  μ = {mu_cal:.2f}°C,  σ = {sigma_cal:.4f}")

        # --- Calibrate humidity ---
        print("  Fitting humidity model …")
        a_hum, b_hum, noise_hum = calibrate_humidity_model(intel_temp, intel_hum)
        print(f"    h = {a_hum:.2f} + {b_hum:.4f}·T,  noise σ = {noise_hum:.2f}")

        # --- Calibrate light ---
        print("  Fitting light mixture model …")
        mu1_l, sig1_l, w_dark, mu2_l, sig2_l = calibrate_light_model(intel_light)
        print(f"    Dark mode:  μ₁={mu1_l:.1f}, σ₁={sig1_l:.1f}, w={w_dark:.3f}")
        print(f"    Bright mode: μ₂={mu2_l:.1f}, σ₂={sig2_l:.1f}")

        # --- Calibrate voltage ---
        volt_mu = float(np.mean(intel_volt))
        volt_sig = float(np.std(intel_volt))
        print(f"  Voltage calibrated: μ = {volt_mu:.3f}V,  σ = {volt_sig:.3f}V")

        # --- Generate calibrated traces ---
        print("\n  Generating calibrated STGen traces …")
        np.random.seed(SEED)
        random.seed(SEED)
        cal_temp, cal_hum = generate_calibrated_mvou_temp_hum(
            N_STGEN_SAMPLES, N_STGEN_MOTES, theta_cal, sigma_cal,
            a_hum, b_hum, noise_hum, intel_temp)
        cal_light = generate_calibrated_light(
            N_STGEN_SAMPLES, mu1_l, sig1_l, w_dark, mu2_l, sig2_l)
        cal_volt = generate_calibrated_voltage(N_STGEN_SAMPLES, intel_volt)

        # --- Compute calibrated metrics ---
        cal_results = {}
        cal_modalities = {
            "temperature": (intel_temp, cal_temp, "°C"),
            "humidity": (intel_hum, cal_hum, "%"),
            "light": (intel_light, cal_light, "lux"),
            "voltage": (intel_volt, cal_volt, "V"),
        }
        for mod, (real, synth, unit) in cal_modalities.items():
            cal_results[mod] = {
                "intel": compute_moments(real),
                "stgen_cal": compute_moments(synth),
                "ks": ks_test(real, synth),
                "jsd": js_divergence(real, synth),
                "unit": unit,
            }

        # Calibrated ACF: MVOU with Cholesky-correlated noise
        rho_cal = -0.38
        theta_H_cal = 0.001
        sigma_H_cal = noise_hum * 0.05
        cal_temp_series = np.zeros(STGEN_DURATION_STEPS)
        cal_hum_series = np.zeros(STGEN_DURATION_STEPS)
        ct = mu_cal
        ch = a_hum + b_hum * mu_cal
        dW1_cal = np.random.normal(0, 1.0, STGEN_DURATION_STEPS)
        dW2_cal = np.random.normal(0, 1.0, STGEN_DURATION_STEPS)
        dZ_T_cal = dW1_cal
        dZ_H_cal = rho_cal * dW1_cal + math.sqrt(1 - rho_cal**2) * dW2_cal
        for i in range(STGEN_DURATION_STEPS):
            dT = theta_cal * (mu_cal - ct) + sigma_cal * dZ_T_cal[i]
            max_rate = 0.5 / 60
            dT = max(-max_rate, min(max_rate, dT))
            ct += dT
            target_h = a_hum + b_hum * ct
            ch += theta_H_cal * (target_h - ch) + sigma_H_cal * dZ_H_cal[i]
            ch = max(0.0, min(100.0, ch))
            cal_temp_series[i] = ct
            cal_hum_series[i] = ch
        cal_results["temperature"]["stgen_acf"] = compute_acf_lags(cal_temp_series, ACF_LAGS)
        cal_results["humidity"]["stgen_acf"] = compute_acf_lags(cal_hum_series, ACF_LAGS)

        # Light: OU with regime switching (calibrated)
        cal_light_series = np.zeros(STGEN_DURATION_STEPS)
        dark_state = True
        l_c = mu1_l
        for i in range(STGEN_DURATION_STEPS):
            if dark_state:
                if random.random() < 0.02:
                    dark_state = False
                target_l, sig_l = mu1_l, sig1_l * 0.15
            else:
                if random.random() < 0.012:
                    dark_state = True
                target_l, sig_l = mu2_l, sig2_l * 0.14
            l_c = _ou_step(l_c, target_l, theta=0.01, sigma=sig_l,
                           lo=0, hi=100000)
            cal_light_series[i] = l_c
        cal_results["light"]["stgen_acf"] = compute_acf_lags(cal_light_series, ACF_LAGS)

        # Voltage: OU with drift
        cal_volt_series = np.zeros(STGEN_DURATION_STEPS)
        v = volt_mu
        for i in range(STGEN_DURATION_STEPS):
            v_mean_step = volt_mu - 0.00001 * i
            v = _ou_step(v, v_mean_step, theta=0.001, sigma=volt_sig * 0.05,
                         lo=1.5, hi=3.5)
            cal_volt_series[i] = v
        cal_results["voltage"]["stgen_acf"] = compute_acf_lags(cal_volt_series, ACF_LAGS)

        # Copy Intel ACF from earlier results
        for mod in ["temperature", "humidity", "light", "voltage"]:
            cal_results[mod]["intel_acf"] = results[mod]["intel_acf"]

        # Calibrated cross-correlation
        cal_cross_corr = {
            "intel": cross_corr["intel"],
            "stgen_cal": compute_cross_corr(cal_temp, cal_hum),
        }

        # --- Print calibrated results ---
        print("\n┌─────────────────────────────────────────────────────────────────────────────┐")
        print("│  CALIBRATED MARGINAL DISTRIBUTION COMPARISON                                │")
        print("├───────────────┬──────────────────────┬──────────────────────┬────────┬───────┤")
        print("│  Modality     │  Intel Lab (μ ± σ)   │  STGen-Cal (μ ± σ)   │  KS D  │  JSD  │")
        print("├───────────────┼──────────────────────┼──────────────────────┼────────┼───────┤")
        for mod in ["temperature", "humidity", "light", "voltage"]:
            r = cal_results[mod]
            name = mod.capitalize().ljust(13)
            intel_str = f"{r['intel']['mean']:7.2f} ± {r['intel']['std']:6.2f}".ljust(20)
            stgen_str = f"{r['stgen_cal']['mean']:7.2f} ± {r['stgen_cal']['std']:6.2f}".ljust(20)
            ks_str = f"{r['ks']['D']:.4f}"
            jsd_str = f"{r['jsd']:.4f}"
            print(f"│  {name} │  {intel_str} │  {stgen_str} │ {ks_str} │{jsd_str} │")
        print("└───────────────┴──────────────────────┴──────────────────────┴────────┴───────┘")

        # Calibrated ACF
        print("\n  Calibrated ACF at key lags:")
        for mod in ["temperature", "humidity", "light", "voltage"]:
            r = cal_results[mod]
            name = mod.capitalize().ljust(13)
            intel_acf_str = "  ".join([f"{r['intel_acf'].get(l, float('nan')):5.3f}" for l in ACF_LAGS])
            stgen_acf_str = "  ".join([f"{r['stgen_acf'].get(l, float('nan')):5.3f}" for l in ACF_LAGS])
            print(f"    {name}  Intel: {intel_acf_str}   STGen-Cal: {stgen_acf_str}")

        print(f"\n  Calibrated Temp–Humidity r: Intel={cal_cross_corr['intel']:.4f}, "
              f"STGen-Cal={cal_cross_corr['stgen_cal']:.4f}")

        # Calibrated fidelity scores
        print("\n  CALIBRATED FIDELITY SCORECARD:")
        cal_scores = []
        for mod in ["temperature", "humidity", "light", "voltage"]:
            r = cal_results[mod]
            ks_score = 1.0 - r["ks"]["D"]
            jsd_score = 1.0 - min(r["jsd"], 1.0)
            acf_diffs = []
            for l in ACF_LAGS:
                i_acf = r["intel_acf"].get(l, 0)
                s_acf = r["stgen_acf"].get(l, 0)
                if not (math.isnan(i_acf) or math.isnan(s_acf)):
                    acf_diffs.append(abs(i_acf - s_acf))
            acf_score = 1.0 - (np.mean(acf_diffs) if acf_diffs else 0.5)
            composite = (ks_score + jsd_score + acf_score) / 3.0
            cal_scores.append(composite)
            print(f"    {mod.capitalize():13s}:  KS={ks_score:.3f}  JSD={jsd_score:.3f}  ACF={acf_score:.3f}  → Composite={composite:.3f}")

        print(f"\n  Overall Fidelity Score (Calibrated): {np.mean(cal_scores):.3f} / 1.000")
        improvement = (np.mean(cal_scores) - np.mean(overall_scores)) / np.mean(overall_scores) * 100
        print(f"  Improvement over default: +{improvement:.1f}%")

        # --- Calibrated plots ---
        for mod, (real, synth, unit) in cal_modalities.items():
            plot_distribution_comparison(
                real, synth, f"{mod.capitalize()} (Calibrated)", unit,
                OUTPUT_DIR / f"dist_{mod}_calibrated.png")

        for mod in ["temperature", "humidity", "light", "voltage"]:
            r = cal_results[mod]
            plot_acf_comparison(
                r["intel_acf"], r["stgen_acf"], f"{mod.capitalize()} (Calibrated)",
                OUTPUT_DIR / f"acf_{mod}_calibrated.png")

        plot_cross_correlation(
            intel_temp, intel_hum, cal_temp, cal_hum,
            OUTPUT_DIR / "cross_corr_temp_hum_calibrated.png")

        # --- LaTeX: Improvement Table ---
        latex_lines = []
        latex_lines.append(r"% Table: Default vs Calibrated Fidelity Comparison")
        latex_lines.append(r"\begin{table}[htbp]")
        latex_lines.append(r"\centering")
        latex_lines.append(r"\caption{Fidelity improvement: default STGen vs.\ calibrated STGen against Intel Berkeley Lab data.}")
        latex_lines.append(r"\label{tab:fidelity-improvement}")
        latex_lines.append(r"\small")
        latex_lines.append(r"\begin{tabular}{l|rr|rr|rr}")
        latex_lines.append(r"\hline")
        latex_lines.append(r"\textbf{Modality} & \multicolumn{2}{c|}{\textbf{KS $D$ ($\downarrow$)}} & \multicolumn{2}{c|}{\textbf{JSD ($\downarrow$)}} & \multicolumn{2}{c}{\textbf{Composite ($\uparrow$)}} \\")
        latex_lines.append(r" & Default & Calibrated & Default & Calibrated & Default & Calibrated \\")
        latex_lines.append(r"\hline")
        for i, mod in enumerate(["temperature", "humidity", "light", "voltage"]):
            r_def = results[mod]
            r_cal = cal_results[mod]
            name = mod.capitalize()
            latex_lines.append(
                f"{name} & {r_def['ks']['D']:.4f} & {r_cal['ks']['D']:.4f} "
                f"& {r_def['jsd']:.4f} & {r_cal['jsd']:.4f} "
                f"& {overall_scores[i]:.3f} & {cal_scores[i]:.3f} \\\\"
            )
        latex_lines.append(r"\hline")
        latex_lines.append(
            f"\\textbf{{Average}} & & & & "
            f"& {np.mean(overall_scores):.3f} & {np.mean(cal_scores):.3f} \\\\"
        )
        latex_lines.append(r"\hline")
        latex_lines.append(r"\end{tabular}")
        latex_lines.append(r"\end{table}")

        with open(OUTPUT_DIR / "fidelity_improvement_table.tex", "w") as f:
            f.write("\n".join(latex_lines) + "\n")

        # --- Calibration parameters JSON ---
        cal_params = {
            "temperature_ou": {"theta": theta_cal, "mu": mu_cal, "sigma": sigma_cal},
            "humidity_linear": {"a": a_hum, "b": b_hum, "noise_std": noise_hum},
            "light_mixture": {
                "dark_mu": mu1_l, "dark_sigma": sig1_l, "dark_weight": w_dark,
                "bright_mu": mu2_l, "bright_sigma": sig2_l
            },
            "voltage": {"mu": volt_mu, "sigma": volt_sig},
        }
        with open(OUTPUT_DIR / "calibrated_parameters.json", "w") as f:
            json.dump(cal_params, f, indent=2)
        print(f"\n  Calibrated parameters → {OUTPUT_DIR / 'calibrated_parameters.json'}")

        # Update JSON results with calibrated data
        json_results["calibrated_marginal"] = {}
        for mod in ["temperature", "humidity", "light", "voltage"]:
            r = cal_results[mod]
            json_results["calibrated_marginal"][mod] = {
                "stgen_calibrated": r["stgen_cal"],
                "ks_D": r["ks"]["D"],
                "ks_p": r["ks"]["p"],
                "jsd": r["jsd"],
            }
        json_results["calibrated_params"] = cal_params
        json_results["fidelity_scores"] = {
            "default": {mod: overall_scores[i] for i, mod in enumerate(["temperature", "humidity", "light", "voltage"])},
            "calibrated": {mod: cal_scores[i] for i, mod in enumerate(["temperature", "humidity", "light", "voltage"])},
            "default_overall": float(np.mean(overall_scores)),
            "calibrated_overall": float(np.mean(cal_scores)),
        }

    with open(OUTPUT_DIR / "fidelity_results.json", "w") as f:
        json.dump(json_results, f, indent=2)
    print(f"  JSON results → {OUTPUT_DIR / 'fidelity_results.json'}")

    print(f"\nAll outputs saved to: {OUTPUT_DIR}/")
    print("Files:")
    for f in sorted(OUTPUT_DIR.iterdir()):
        print(f"  {f.name}")


if __name__ == "__main__":
    main()
